name: advanced_camera_app
description: An advanced camera application with professional features built with Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Camera and Media
  camera: ^0.10.5+5
  image: ^4.1.3
  path_provider: ^2.1.1
  gallery_saver: ^2.3.2
  
  # Permissions
  permission_handler: ^11.0.1
  
  # Storage and Database
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  
  # Network and HTTP
  http: ^1.1.0
  dio: ^5.3.2
  
  # Functional Programming
  dartz: ^0.10.1
  
  # Utilities
  uuid: ^4.2.1
  
  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2
  
  # UI and Navigation
  go_router: ^12.1.1
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  
  # Utilities
  intl: ^0.18.1
  
  # Security
  flutter_secure_storage: ^9.0.0
  crypto: ^3.0.3
  
  # Image Processing
  image_picker: ^1.0.4
  photo_manager: ^3.0.0
  
  # Social Sharing
  share_plus: ^7.2.1
  
  # Cloud Storage (optional)
  firebase_core: ^2.24.2
  firebase_storage: ^11.5.6
  
  # Platform Specific
  device_info_plus: ^9.1.0
  package_info_plus: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1
  
  # Testing
  mockito: ^5.4.2
  bloc_test: ^9.1.4
  
  # Linting
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/filters/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true